// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: rpc_update_user_name.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     *string                `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserNameRequest) Reset() {
	*x = UpdateUserNameRequest{}
	mi := &file_rpc_update_user_name_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserNameRequest) ProtoMessage() {}

func (x *UpdateUserNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_user_name_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserNameRequest) Descriptor() ([]byte, []int) {
	return file_rpc_update_user_name_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserNameRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserNameRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateUserNameRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

type UpdateUserNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserNameResponse) Reset() {
	*x = UpdateUserNameResponse{}
	mi := &file_rpc_update_user_name_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserNameResponse) ProtoMessage() {}

func (x *UpdateUserNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_user_name_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserNameResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserNameResponse) Descriptor() ([]byte, []int) {
	return file_rpc_update_user_name_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserNameResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_rpc_update_user_name_proto protoreflect.FileDescriptor

const file_rpc_update_user_name_proto_rawDesc = "" +
	"\n" +
	"\x1arpc_update_user_name.proto\x12\x02pb\x1a\n" +
	"user.proto\"\x93\x01\n" +
	"\x15UpdateUserNameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\"\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x01R\blastName\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name\"6\n" +
	"\x16UpdateUserNameResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x01(\v2\b.pb.UserR\x04userB8Z6github.com/DebdipWritesCode/VisitorManagementSystem/pbb\x06proto3"

var (
	file_rpc_update_user_name_proto_rawDescOnce sync.Once
	file_rpc_update_user_name_proto_rawDescData []byte
)

func file_rpc_update_user_name_proto_rawDescGZIP() []byte {
	file_rpc_update_user_name_proto_rawDescOnce.Do(func() {
		file_rpc_update_user_name_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_update_user_name_proto_rawDesc), len(file_rpc_update_user_name_proto_rawDesc)))
	})
	return file_rpc_update_user_name_proto_rawDescData
}

var file_rpc_update_user_name_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_update_user_name_proto_goTypes = []any{
	(*UpdateUserNameRequest)(nil),  // 0: pb.UpdateUserNameRequest
	(*UpdateUserNameResponse)(nil), // 1: pb.UpdateUserNameResponse
	(*User)(nil),                   // 2: pb.User
}
var file_rpc_update_user_name_proto_depIdxs = []int32{
	2, // 0: pb.UpdateUserNameResponse.user:type_name -> pb.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_update_user_name_proto_init() }
func file_rpc_update_user_name_proto_init() {
	if File_rpc_update_user_name_proto != nil {
		return
	}
	file_user_proto_init()
	file_rpc_update_user_name_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_update_user_name_proto_rawDesc), len(file_rpc_update_user_name_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_update_user_name_proto_goTypes,
		DependencyIndexes: file_rpc_update_user_name_proto_depIdxs,
		MessageInfos:      file_rpc_update_user_name_proto_msgTypes,
	}.Build()
	File_rpc_update_user_name_proto = out.File
	file_rpc_update_user_name_proto_goTypes = nil
	file_rpc_update_user_name_proto_depIdxs = nil
}
