DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "otps" CASCADE;
DROP TABLE IF EXISTS "appointment_logs" CASCADE;
DROP TYPE IF EXISTS "appointment_stats" CASCADE;
DROP TYPE IF EXISTS "availability" CASCADE;
DROP TYPE IF EXISTS "appointments" CASCADE;
