CREATE TABLE "otps" (
  "phone_number" varchar(15),
  "otp_code" varchar(6),
  "created_at" timestamp DEFAULT (now()),
  "expires_at" timestamp
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone_number" varchar(15) UNIQUE NOT NULL,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "role" varchar(10) DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  "created_at" timestamp DEFAULT (now()),
  "appointments_hosted" integer DEFAULT 0,
  "appointments_visited" integer DEFAULT 0
);

CREATE TABLE "availability" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "day_of_week" INTEGER NOT NULL CHECK (day_of_week BETWEEN 1 AND 5),
  "start_time" TIME NOT NULL,
  "end_time" TIME NOT NULL,
  "status" VARCHAR(20) DEFAULT 'available' CHECK (status IN ('available', 'not_available')),
  UNIQUE ("user_id", "day_of_week", "start_time", "end_time"),
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE TABLE "appointments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "visitor_id" integer NOT NULL,
  "host_id" integer NOT NULL,
  "appointment_date" date NOT NULL,
  "start_time" time NOT NULL,
  "end_time" time NOT NULL,
  "status" varchar(10) DEFAULT 'pending' CHECK (status IN ('pending', 'ongoing', 'completed', 'cancelled')),
  "qr_code" text,
  "created_at" timestamp DEFAULT (now()),
  FOREIGN KEY ("visitor_id") REFERENCES "users" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("host_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE TABLE "appointment_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appointment_id" integer NOT NULL,
  "check_in_time" timestamp,
  "check_out_time" timestamp,
  FOREIGN KEY ("appointment_id") REFERENCES "appointments" ("id") ON DELETE CASCADE
);

CREATE TABLE "appointment_stats" (
  "user_id" integer PRIMARY KEY,
  "total_appointments" integer DEFAULT 0,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);
