CREATE TYPE "Role" AS ENUM (
  'admin',
  'user'
);

CREATE TYPE "AppointmentStatus" AS ENUM (
  'pending',
  'ongoing',
  'completed',
  'cancelled'
);

CREATE TABLE "otps" (
  "phone_number" varchar(15),
  "otp_code" varchar(6),
  "created_at" timestamp DEFAULT (now()),
  "expires_at" timestamp
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone_number" varchar(15) UNIQUE NOT NULL,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "role" Role DEFAULT 'user',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "availability" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "day_of_week" integer NOT NULL CHECK (day_of_week BETWEEN 1 AND 5),
  "start_time" time NOT NULL,
  "end_time" time NOT NULL,
  UNIQUE ("user_id", "day_of_week", "start_time", "end_time"),
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE TABLE "appointments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "visitor_id" integer NOT NULL,
  "host_id" integer NOT NULL,
  "appointment_date" date NOT NULL,
  "start_time" time NOT NULL,
  "end_time" time NOT NULL,
  "status" AppointmentStatus DEFAULT 'pending',
  "qr_code" text,
  "created_at" timestamp DEFAULT (now()),
  FOREIGN KEY ("visitor_id") REFERENCES "users" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("host_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE TABLE "appointment_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appointment_id" integer NOT NULL,
  "check_in_time" timestamp,
  "check_out_time" timestamp,
  FOREIGN KEY ("appointment_id") REFERENCES "appointments" ("id") ON DELETE CASCADE
);

CREATE TABLE "appointment_stats" (
  "user_id" integer PRIMARY KEY,
  "total_appointments" integer DEFAULT 0,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);
