// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Appointment struct {
	ID              int32          `json:"id"`
	VisitorID       int32          `json:"visitor_id"`
	HostID          int32          `json:"host_id"`
	AppointmentDate time.Time      `json:"appointment_date"`
	StartTime       time.Time      `json:"start_time"`
	EndTime         time.Time      `json:"end_time"`
	Status          sql.NullString `json:"status"`
	QrCode          sql.NullString `json:"qr_code"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type AppointmentLog struct {
	ID            int32        `json:"id"`
	AppointmentID int32        `json:"appointment_id"`
	CheckInTime   sql.NullTime `json:"check_in_time"`
	CheckOutTime  sql.NullTime `json:"check_out_time"`
}

type AppointmentStat struct {
	UserID            int32         `json:"user_id"`
	TotalAppointments sql.NullInt32 `json:"total_appointments"`
}

type Availability struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	DayOfWeek int32          `json:"day_of_week"`
	StartTime time.Time      `json:"start_time"`
	EndTime   time.Time      `json:"end_time"`
	Status    sql.NullString `json:"status"`
}

type Otp struct {
	PhoneNumber sql.NullString `json:"phone_number"`
	OtpCode     sql.NullString `json:"otp_code"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
}

type User struct {
	ID                  int32          `json:"id"`
	PhoneNumber         string         `json:"phone_number"`
	FirstName           string         `json:"first_name"`
	LastName            string         `json:"last_name"`
	Role                sql.NullString `json:"role"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	AppointmentsHosted  sql.NullInt32  `json:"appointments_hosted"`
	AppointmentsVisited sql.NullInt32  `json:"appointments_visited"`
}
