// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	CancelAppointment(ctx context.Context, id int32) (Appointment, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateAppointmentLog(ctx context.Context, arg CreateAppointmentLogParams) (AppointmentLog, error)
	CreateAppointmentStats(ctx context.Context, arg CreateAppointmentStatsParams) (AppointmentStat, error)
	CreateAvailabilitySlot(ctx context.Context, arg CreateAvailabilitySlotParams) (Availability, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (Otp, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementAppointmentCount(ctx context.Context, userID int32) (AppointmentStat, error)
	DeleteAppointment(ctx context.Context, id int32) error
	DeleteAppointmentLog(ctx context.Context, appointmentID int32) error
	DeleteAppointmentStats(ctx context.Context, userID int32) error
	DeleteAvailabilityByUser(ctx context.Context, userID int32) error
	DeleteAvailabilitySlot(ctx context.Context, arg DeleteAvailabilitySlotParams) error
	DeleteExpiredOTPs(ctx context.Context) error
	DeleteOTPByPhone(ctx context.Context, phoneNumber sql.NullString) error
	DeleteUser(ctx context.Context, id int32) error
	GetAppointmentByID(ctx context.Context, id int32) (Appointment, error)
	GetAppointmentByQRCode(ctx context.Context, qrCode sql.NullString) (GetAppointmentByQRCodeRow, error)
	GetAppointmentLogByAppointmentID(ctx context.Context, appointmentID int32) (AppointmentLog, error)
	GetAppointmentStatsByUserID(ctx context.Context, userID int32) (AppointmentStat, error)
	GetAvailabilityByUser(ctx context.Context, userID int32) ([]Availability, error)
	GetOTPByPhone(ctx context.Context, phoneNumber sql.NullString) (Otp, error)
	GetTopPopularUsers(ctx context.Context) ([]GetTopPopularUsersRow, error)
	GetTotalAppointmentsHosted(ctx context.Context, id int32) (sql.NullInt32, error)
	GetTotalAppointmentsVisited(ctx context.Context, id int32) (sql.NullInt32, error)
	GetUserAppointmentStats(ctx context.Context, id int32) (GetUserAppointmentStatsRow, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByPhone(ctx context.Context, phoneNumber string) (User, error)
	GetUsersByName(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	IncrementAppointmentCount(ctx context.Context, userID int32) (AppointmentStat, error)
	ListAppointmentsByDate(ctx context.Context, appointmentDate time.Time) ([]ListAppointmentsByDateRow, error)
	ListAppointmentsByHost(ctx context.Context, hostID int32) ([]ListAppointmentsByHostRow, error)
	ListAppointmentsByVisitor(ctx context.Context, visitorID int32) ([]ListAppointmentsByVisitorRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ResetAppointmentCount(ctx context.Context, userID int32) (AppointmentStat, error)
	UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error)
	UpdateAvailabilityStatus(ctx context.Context, arg UpdateAvailabilityStatusParams) error
	UpdateCheckInTime(ctx context.Context, arg UpdateCheckInTimeParams) (AppointmentLog, error)
	UpdateCheckOutTime(ctx context.Context, arg UpdateCheckOutTimeParams) (AppointmentLog, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
